codecov:
  require_ci_to_pass: true

coverage:
  paths:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

fixes:
  - "/home/circleci/::"
  - "/home/runner/work/kickflip-src/::"
  - "/Users/danpock/GitProjects/::"

ignore:
  - "packages/**/node_modules/*"