codecov:
  require_ci_to_pass: true

coverage:
  paths:
  precision: 2
  round: up
  range: "70...100"
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:  # declare a new status context "tests"
        target: 92%  # we always want 100% coverage here
        paths: "tests/"  # only include coverage in "tests/" folder
      app:  # declare a new status context "app"
        paths: "!tests/"  # remove all files in "tests/"
    patch:
      default:
        target: auto
        threshold: 12%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false

fixes:
  - "/home/circleci/::"
  - "/home/runner/work/kickflip-src/::"
  - "/Users/danpock/GitProjects/::"

ignore:
  - "packages/**/node_modules/*"