name: Run tests

on:
    push:
    schedule:
        - cron: '0 0 * * *'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [8.1, 8.0]
                laravel: [8.*]
                dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest]
                include:
                    - laravel: 8.*
                      zero: ^8.9.0

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" "laravel-zero/framework:${{ matrix.zero }}" --no-interaction --no-update
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest
