name: Run tests

on:
    push:
        paths:
            - packages/kickflip/**/*.php
            - packages/kickflip-cli/**/*.php
            - packages/kickflip-docs/**/*.php
            - tests/**/*.php
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php: [8.1, 8.0]
                laravel: [8.*]
                dependency-version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest]

        name: TEST - P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none

            - name: Setup and build node deps
              run: cd packages/kickflip-docs && npm install && npm run dev && cd

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install dependencies
              run: |
                  composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/pest
