name: Split Monorepo

on:
    push:
        branches:
            - main
        tags:
            - '*'

env:
    # 1. for Github split
    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
    provide_packages_json:
        # see json juggling: https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#example-6
        # see https://stackoverflow.com/a/62953566/1348344
        runs-on: ubuntu-latest

        steps:
            - name: Wait for tests to succeed
              uses: lewagon/wait-on-check-action@v1.1.1
              with:
                  ref: ${{ github.ref }}
                  check-name: 'Run tests'
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  wait-interval: 600
            -   uses: actions/checkout@v2

            # required for matrix of packages set
            -   uses: shivammathur/setup-php@v2.2.0
                with:
                    php-version: 8.0
                    coverage: none

            -   uses: "ramsey/composer-install@v1"

            # get package json list
            -
                id: output_data
                run: echo "::set-output name=matrix::$(vendor/bin/monorepo-builder packages-json --exclude-package easy-coding-standard --exclude-package monorepo-builder --exclude-package config-transformer)"

        # this step is needed, so the output gets to the next defined job
        outputs:
            matrix: ${{ steps.output_data.outputs.matrix }}

    split_monorepo:
        needs: provide_packages_json

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                package: ${{fromJson(needs.provide_packages_json.outputs.matrix)}}

        steps:
            -   uses: actions/checkout@v2

            # no tag
            -
                if: "!startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'mallardduck'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "MallardDuck"
                    user-email: "self@danpock.me"
                    branch: "main"

            # with tag
            -
                if: "startsWith(github.ref, 'refs/tags/')"
                # Uses an action in the root directory
                name: Monorepo Tagged Split of ${{ matrix.package }}
                uses: symplify/github-action-monorepo-split@2.1
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                with:
                    tag: ${GITHUB_REF#refs/tags/}

                    package-directory: 'packages/${{ matrix.package }}'
                    split-repository-organization: 'mallardduck'
                    split-repository-name: '${{ matrix.package }}'
                    user-name: "MallardDuck"
                    user-email: "self@danpock.me"
                    branch: "main"
